@Catalog_HostAddress = https://localhost:7028/products

GET {{Catalog_HostAddress}}/
Accept: application/json

###

GET {{Catalog_HostAddress}}/1
Accept: application/json

###

POST {{Catalog_HostAddress}}/
Content-Type: application/json
{
  "id": 10,
  "name": "NEW SUn Flashlight",
  "description": "Test Product Description",
  "price": 100.0,
  "imageUrl": "Product10.png"
}

###

PUT {{Catalog_HostAddress}}/10
Content-Type: application/json
{
  "id": 10,
  "name": "UPDATED Sun Flashlist",
  "description": "Test Product Description",
  "price": 55.0,
  "imageUrl": "Product10.png"
}

###

DELETE {{Catalog_HostAddress}}/10 
Content-Type: application/json
